name: dev
services:
  traefik:
    image: traefik:1.7-alpine
    container_name: traefik
    restart: always
    command:
      - --docker.domain=${DOMAIN:-lvh.me}
      - --docker.network=traefik
      - --api.dashboard
    labels:
      - "traefik.frontend.rule=Host:traefik.${DOMAIN:-lvh.me}"
      - "traefik.port=8080"
    ports:
      - ${PROXY_PORT:-80}:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  adminer:
    image: adminer
    ports:
    - 8080
  www:
    image: nginx
    ports:
    - 80
    volumes:
    - www:/usr/share/nginx/html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 1s
      retries: 0
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: s3cr3t
    volumes:
    - etlapdb:/var/lib/mysql
    - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 3s
      retries: 3

  generator:
    build: generator
    image: ttl.sh/generator
    init: true
    environment:
      TITLE: ${TITLE:-Menu [dev]}
    depends_on:
      db:
        condition: service_healthy
    volumes:
    -  www:/www

volumes:
  www:
  etlapdb:

networks:
  traefik:
    external: true