services:
  www:
    image: nginx
    ports:
    - 80
    volumes:
    - www:/usr/share/nginx/html

  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: s3cr3t
    volumes:
    - etlapdb:/var/lib/mysql
    - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  adminer:
    image: adminer
    ports:
    - 8080
  generator:
    image: ttl.sh/generator
    depends_on:
     db:
      condition: service_healthy
    environment:
    volumes:
    -  www:/www

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080

volumes:
  www:
  etlapdb: