services:
  www:
    image: nginx
    ports:
    - 80
    volumes:
    - www:/usr/share/nginx/html
    labels:
      - "traefik.frontend.rule=Host:www.${DOMAIN}"

  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: s3cr3t
    volumes:
    - etlapdb:/var/lib/mysql
    - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  adminer:
    image: adminer
    ports:
    - 8080
    labels:
      - "traefik.frontend.rule=Host:adminer.${DOMAIN}"

  generator:
    build: generator
    image: ttl.sh/generator
    init: true
    depends_on:
     db:
      condition: service_healthy
    environment:
    - TRACE=1
    - TITLE=Wednesday Menu
    volumes:
    -  www:/www

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}

  traefik:
    image: traefik:1.7-alpine
    container_name: traefik
    restart: always
    command:
      - --retry
      #- --debug
      - --rest
      - --docker.domain=${DOMAIN}
      - --docker.network=traefik
      - --api.dashboard
    labels:
      - "traefik.frontend.rule=Host:traefik.${DOMAIN}"
      - "traefik.port=8080"
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080

volumes:
  www:
  etlapdb:
networks:
  traefik:
    external: true