services:

  traefik:
    image: traefik:1.7-alpine
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.frontend.rule=Host:traefik.${DOMAIN:-lvh.me}"
        - "traefik.port=8080"

    command:
      - --docker.domain=${DOMAIN:-lvh.me}
      - --docker.network=traefik
      - --api.dashboard
      - --docker.swarmMode
    # labels:
    #   - "traefik.frontend.rule=Host:traefik.${DOMAIN:-lvh.me}"
    #   - "traefik.port=8080"
    ports:
      - 44444:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  coffee:
    image: ttl.sh/12factor
    ports:
    - 54321:80
    configs:
      - source: title
        target: /etc/myapp/title
    secrets:
      - source: color
        target: /etc/myapp/color
    deploy:
      replicas: 3
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:coffee.${DOMAIN:-lvh.me}"
        - "traefik.port=80"
    environment:
      TITLE: ${TITLE:-Coffee [swarm-dev]}
      COLOR2: ${COLOR:-lime}

configs:
  title:
    external:
      name: ${ENV:-dev}_title

secrets:
  color:
    external:
      name: ${ENV:-dev}_color

networks:
  default:
    name: traefik